services:
  edu-plus:
    build:
      context: .
      dockerfile: apps/edu-plus/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET:-danger}
      - EDUCORE_URL=http://edu-core:3001
      - NODE_ENV=production
    depends_on:
      - edu-core

  edu-core:
    build:
      context: .
      dockerfile: apps/edu-core/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EDUCORE_PORT=3001
      - NODE_ENV=production
