// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const isProduction = process.env.NODE_ENV === 'production';
const databaseUrl = process.env.DATABASE_URL;
const prismaDb = process.env.PRISMA_DATABASE_URL;
const dbToUse = isProduction ? prismaDb : databaseUrl;

export default defineConfig({
  schema: './src/prisma/schema.prisma',
  migrations: {
    path: './src/prisma/migrations',
    seed: 'tsx ./src/prisma/seed.ts',
  },
  datasource: {
    url: dbToUse,
  },
});
