// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const isProduction = process.env.NODE_ENV === 'production';
const databaseUrl = process.env.DATABASE_URL;
const prismaDb = process.env.POSTGRES_URL || databaseUrl;
const dbToUse = isProduction ? prismaDb : databaseUrl;

export default defineConfig({
  schema: './libs/prisma-client/prisma/schema.prisma',
  migrations: {
    path: './libs/prisma-client/prisma/migrations',
    seed: 'tsx ./libs/prisma-client/prisma/seed.ts',
  },
  datasource: {
    url: dbToUse,
  },
});
